## This file is a general .xdc for the Basys3 rev B board
## To use it in a project:
## - uncomment the lines corresponding to used pins
## - rename the used ports (in each line, after get_ports) according to the top level signal names in the project

## Switches
#set_property PACKAGE_PIN V17 [get_ports {pixelDATA[0]}]					
#	set_property IOSTANDARD LVCMOS33 [get_ports {pixelDATA[0]}]
#set_property PACKAGE_PIN V16 [get_ports {pixelDATA[1]}]					
#	set_property IOSTANDARD LVCMOS33 [get_ports {pixelDATA[1]}]
#set_property PACKAGE_PIN W16 [get_ports {pixelDATA[2]}]					
#	set_property IOSTANDARD LVCMOS33 [get_ports {pixelDATA[2]}]
#set_property PACKAGE_PIN W17 [get_ports {pixelDATA[3]}]					
#	set_property IOSTANDARD LVCMOS33 [get_ports {pixelDATA[3]}]
#set_property PACKAGE_PIN W15 [get_ports {pixelDATA[4]}]					
#	set_property IOSTANDARD LVCMOS33 [get_ports {pixelDATA[4]}]
#set_property PACKAGE_PIN V15 [get_ports {pixelDATA[5]}]					
#	set_property IOSTANDARD LVCMOS33 [get_ports {pixelDATA[5]}]
#set_property PACKAGE_PIN W14 [get_ports {pixelDATA[6]}]					
#	set_property IOSTANDARD LVCMOS33 [get_ports {pixelDATA[6]}]
#set_property PACKAGE_PIN W13 [get_ports {pixelDATA[7]}]					
#	set_property IOSTANDARD LVCMOS33 [get_ports {pixelDATA[7]}]
#set_property PACKAGE_PIN V2 [get_ports {pixelDATA[8]}]					
#	set_property IOSTANDARD LVCMOS33 [get_ports {pixelDATA[8]}]
#set_property PACKAGE_PIN T3 [get_ports {pixelDATA[9]}]					
#	set_property IOSTANDARD LVCMOS33 [get_ports {pixelDATA[9]}]
#set_property PACKAGE_PIN T2 [get_ports {pixelDATA[10]}]					
#	set_property IOSTANDARD LVCMOS33 [get_ports {pixelDATA[10]}]
#set_property PACKAGE_PIN R3 [get_ports {pixelDATA[11]}]					
#	set_property IOSTANDARD LVCMOS33 [get_ports {pixelDATA[11]}]


#set_property PACKAGE_PIN W2 [get_ports {vgaTEST}]					
#	set_property IOSTANDARD LVCMOS33 [get_ports {vgaTEST}]
#set_property PACKAGE_PIN U1 [get_ports {vgaMODE[0]}]					
#	set_property IOSTANDARD LVCMOS33 [get_ports {vgaMODE[0]}]
#set_property PACKAGE_PIN T1 [get_ports {vgaMODE[1]}]					
#	set_property IOSTANDARD LVCMOS33 [get_ports {vgaMODE[1]}]
set_property PACKAGE_PIN R2 [get_ports {EN}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {EN}]
 

## LEDs
#set_property PACKAGE_PIN U16 [get_ports {sysCLK}]					
#	set_property IOSTANDARD LVCMOS33 [get_ports {sysCLK}]
#set_property PACKAGE_PIN E19 [get_ports {vgaCLK}]					
#	set_property IOSTANDARD LVCMOS33 [get_ports {vgaCLK}]
#set_property PACKAGE_PIN V19 [get_ports {vgaLOCK}]					
#	set_property IOSTANDARD LVCMOS33 [get_ports {vgaLOCK}]
#set_property PACKAGE_PIN W18 [get_ports {sysLOCK}]					
#	set_property IOSTANDARD LVCMOS33 [get_ports {sysLOCK}]		


#set_property PACKAGE_PIN U16 [get_ports {led[0]}]					
	#set_property IOSTANDARD LVCMOS33 [get_ports {led[0]}]
#set_property PACKAGE_PIN E19 [get_ports {led[1]}]					
	#set_property IOSTANDARD LVCMOS33 [get_ports {led[1]}]
#set_property PACKAGE_PIN U19 [get_ports {led[2]}]					
	#set_property IOSTANDARD LVCMOS33 [get_ports {led[2]}]
#set_property PACKAGE_PIN V19 [get_ports {led[3]}]					
	#set_property IOSTANDARD LVCMOS33 [get_ports {led[3]}]
#set_property PACKAGE_PIN W18 [get_ports {led[4]}]					
	#set_property IOSTANDARD LVCMOS33 [get_ports {led[4]}]
#set_property PACKAGE_PIN U15 [get_ports {led[5]}]					
	#set_property IOSTANDARD LVCMOS33 [get_ports {led[5]}]
#set_property PACKAGE_PIN U14 [get_ports {led[6]}]					
	#set_property IOSTANDARD LVCMOS33 [get_ports {led[6]}]
#set_property PACKAGE_PIN V14 [get_ports {led[7]}]					
	#set_property IOSTANDARD LVCMOS33 [get_ports {led[7]}]
#set_property PACKAGE_PIN V13 [get_ports {led[8]}]					
	#set_property IOSTANDARD LVCMOS33 [get_ports {led[8]}]
#set_property PACKAGE_PIN V3 [get_ports {led[9]}]					
	#set_property IOSTANDARD LVCMOS33 [get_ports {led[9]}]
#set_property PACKAGE_PIN W3 [get_ports {led[10]}]					
	#set_property IOSTANDARD LVCMOS33 [get_ports {led[10]}]
#set_property PACKAGE_PIN U3 [get_ports {led[11]}]					
	#set_property IOSTANDARD LVCMOS33 [get_ports {led[11]}]
#set_property PACKAGE_PIN P3 [get_ports {led[12]}]					
	#set_property IOSTANDARD LVCMOS33 [get_ports {led[12]}]
#set_property PACKAGE_PIN N3 [get_ports {led[13]}]					
	#set_property IOSTANDARD LVCMOS33 [get_ports {led[13]}]
#set_property PACKAGE_PIN P1 [get_ports {led[14]}]					
	#set_property IOSTANDARD LVCMOS33 [get_ports {led[14]}]
#set_property PACKAGE_PIN L1 [get_ports {led[15]}]					
	#set_property IOSTANDARD LVCMOS33 [get_ports {led[15]}]


##Buttons
set_property PACKAGE_PIN U18 [get_ports RESET]						
	set_property IOSTANDARD LVCMOS33 [get_ports RESET]
#set_property PACKAGE_PIN T18 [get_ports btnU]						
	#set_property IOSTANDARD LVCMOS33 [get_ports btnU]
#set_property PACKAGE_PIN W19 [get_ports btnL]						
	#set_property IOSTANDARD LVCMOS33 [get_ports btnL]
#set_property PACKAGE_PIN T17 [get_ports btnR]						
	#set_property IOSTANDARD LVCMOS33 [get_ports btnR]
#set_property PACKAGE_PIN U17 [get_ports btnD]						
	#set_property IOSTANDARD LVCMOS33 [get_ports btnD]